# flask-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
  namespace: flask-app
type: Opaque
data:
  PGDB_USER: cG9zdGdyZXM=    # Base64 of "postgres"
  PGDB_PASSWORD: cGFzc3dvcmQ= # Base64 of "password"
  PGDB_NAME: bXlkYg==        # Base64 of "mydb"
