# redis-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-cache-service
  namespace: redis-cache
spec:
  selector:
    app: redis-cache
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP